/**
 * The endpoint policy registry (DEC-070, docs/SECURITY_MODEL.md).
 *
 * Every route the API serves is declared here, once, with its security
 * policy. The HTTP layer (app.ts) registers routes FROM this list: the
 * authentication middleware is chosen by `auth` (and `scope`), never by the
 * shape of the path. Tests check that every contract route has a policy,
 * that every policy has a handler, and they exercise the declared policy
 * (no session → 401; applicant on a member route → 403; member session on an
 * internal route → 401). docs/SECURITY_MODEL.md's endpoint table is generated
 * from this file (npm run docs:security) and checked for drift by a test.
 *
 * Fields
 *   auth           none | session | token-optional | signed-url | internal
 *   scope          the internal key scope required (internal only)
 *   membership     what the caller must be: NONE (anyone) · ACCOUNT (any signed-in
 *                  person) · APPLICATION (an applicant with an application) ·
 *                  ACTIVE_MEMBER (ACTIVE_MEMBER + live membership, checked inside
 *                  the operation's transaction) · BY_MEDIA_CLASS (per class)
 *   ownership      whose data the operation may touch
 *   authorization  the rule decided server-side, beyond membership
 *   validation     what is validated before anything happens
 *   response       the DTO answered (never a row)
 *   errors         typed error codes the endpoint can answer
 *   limits         rate limits (PostgreSQL-backed, shared by every instance)
 */
import type { ApiErrorCode } from '@/services/api/contract';
import type { InternalScope } from '../config';

export type AuthKind = 'none' | 'session' | 'token-optional' | 'signed-url' | 'internal';
export type MembershipRequirement = 'NONE' | 'ACCOUNT' | 'APPLICATION' | 'ACTIVE_MEMBER' | 'BY_MEDIA_CLASS';
export type Method = 'GET' | 'POST' | 'PUT' | 'PATCH';

export type EndpointPolicy = {
  method: Method;
  path: string;
  auth: AuthKind;
  scope?: InternalScope;
  membership: MembershipRequirement;
  ownership: string;
  authorization: string;
  validation: string;
  response: string;
  errors: readonly ApiErrorCode[];
  limits?: readonly string[];
  /** Maximum request body in bytes (default: 64 KiB of JSON). */
  bodyLimit?: number;
  /** Served only when this holds for the running configuration. */
  when?: 'local-storage' | 'not-production';
};

const AUTHN: readonly ApiErrorCode[] = ['UNAUTHENTICATED'];
const BASE: readonly ApiErrorCode[] = ['UNAUTHENTICATED', 'VALIDATION_FAILED', 'RATE_LIMITED', 'PAYLOAD_TOO_LARGE', 'INTERNAL'];
const MEMBER: readonly ApiErrorCode[] = [...BASE, 'MEMBERSHIP_REQUIRED'];
const INTERNAL: readonly ApiErrorCode[] = ['UNAUTHENTICATED', 'VALIDATION_FAILED', 'NOT_FOUND', 'NOT_ALLOWED', 'INTERNAL'];
const SELF = 'The caller’s own account (from the session; never from the request).';
const SELF_APP = 'The caller’s own application only (looked up by the session’s account).';
const SELF_MEMBER = 'The caller’s own member profile only (looked up by the session’s account).';

export const ENDPOINTS = {
  // --- Health -------------------------------------------------------------------------------
  'health.live': {
    method: 'GET',
    path: '/health/live',
    auth: 'none',
    membership: 'NONE',
    ownership: 'None.',
    authorization: 'Public. Answers only that the process is serving.',
    validation: 'None.',
    response: '{ status }',
    errors: [],
  },
  'health.ready': {
    method: 'GET',
    path: '/health/ready',
    auth: 'none',
    membership: 'NONE',
    ownership: 'None.',
    authorization: 'Public. Reports pass/fail per dependency only — no versions, hosts, counts or data.',
    validation: 'None.',
    response: '{ status, checks: { database, migrations, storage } }',
    errors: [],
  },
  health: {
    method: 'GET',
    path: '/health',
    auth: 'none',
    membership: 'NONE',
    ownership: 'None.',
    authorization: 'Public. Alias of /health/live.',
    validation: 'None.',
    response: '{ ok }',
    errors: [],
  },

  // --- Authentication ---------------------------------------------------------------------------
  'auth.requestOtp': {
    method: 'POST',
    path: '/v1/auth/otp',
    auth: 'none',
    membership: 'NONE',
    ownership: 'None. The answer is identical whether or not the number has an account.',
    authorization: 'Public.',
    validation: 'phoneE164 matches E.164.',
    response: 'OtpChallenge',
    errors: ['VALIDATION_FAILED', 'INVALID_PHONE', 'RATE_LIMITED', 'CODE_NOT_SENT', 'PAYLOAD_TOO_LARGE', 'INTERNAL'],
    limits: ['otpRequestPerIp', 'otpRequestPerPhone', '30 s resend cooldown per number'],
  },
  'auth.verifyOtp': {
    method: 'POST',
    path: '/v1/auth/otp/verify',
    auth: 'none',
    membership: 'NONE',
    ownership: 'The challenge’s number only.',
    authorization: 'Proof of possession of the code. Suspended / deleted accounts are refused after proof.',
    validation: 'challengeId (≤ 100 chars), code (6 digits).',
    response: 'AuthenticatedApplicant',
    errors: ['VALIDATION_FAILED', 'INVALID_CODE', 'CODE_EXPIRED', 'TOO_MANY_ATTEMPTS', 'RATE_LIMITED', 'NOT_ALLOWED', 'PAYLOAD_TOO_LARGE', 'INTERNAL'],
    limits: ['otpVerifyPerIp', 'otpVerifyPerPhone', '5 attempts per code'],
  },
  'auth.signOut': {
    method: 'POST',
    path: '/v1/auth/sign-out',
    auth: 'token-optional',
    membership: 'NONE',
    ownership: 'The presented token only.',
    authorization: 'Revokes the presented token if it is valid; always answers the same.',
    validation: 'Bearer token format.',
    response: '{ signedOut }',
    errors: ['INTERNAL'],
  },
  'auth.signOutEverywhere': {
    method: 'POST',
    path: '/v1/auth/sign-out-all',
    auth: 'session',
    membership: 'ACCOUNT',
    ownership: SELF,
    authorization: 'Revokes every live session of the caller’s account.',
    validation: 'None.',
    response: '{ signedOut, sessions }',
    errors: [...AUTHN, 'INTERNAL'],
  },
  'auth.rotateSession': {
    method: 'POST',
    path: '/v1/auth/session/rotate',
    auth: 'session',
    membership: 'ACCOUNT',
    ownership: 'The presented session only.',
    authorization: 'A live session is exchanged once; reuse of a rotated token revokes the whole session family.',
    validation: 'Bearer token format.',
    response: 'Session',
    errors: [...AUTHN, 'INTERNAL'],
  },

  // --- Account lifecycle ----------------------------------------------------------------------------
  'account.requestDeletion': {
    method: 'POST',
    path: '/v1/me/deletion',
    auth: 'session',
    membership: 'ACCOUNT',
    ownership: SELF,
    authorization: 'Any signed-in person may delete their own account. Idempotent.',
    validation: '{ confirm: true }.',
    response: '{ deletionRequested }',
    errors: BASE,
    limits: ['accountDeletionPerAccount'],
  },

  // --- Media (direct upload) --------------------------------------------------------------------------
  'media.createUpload': {
    method: 'POST',
    path: '/v1/media/uploads',
    auth: 'session',
    membership: 'BY_MEDIA_CLASS',
    ownership: 'The caller’s own application (APPLICATION_MEDIA, VERIFICATION_MEDIA) or member profile (PROFILE_MEDIA).',
    authorization:
      'APPLICATION_MEDIA: extended draft open, or an open REPLACE_PHOTO request. VERIFICATION_MEDIA: an open VERIFY_IDENTITY request. PROFILE_MEDIA: ACTIVE_MEMBER with a live membership.',
    validation: 'mediaClass, contentType (jpeg/png/webp), byteLength (1 B – 8 MiB), requestId.',
    response: 'UploadAuthorization (10-minute signed PUT url; type and length signed)',
    errors: [...MEMBER, 'NOT_ALLOWED'],
    limits: ['mediaUploadPerAccount'],
  },
  'media.completeUpload': {
    method: 'POST',
    path: '/v1/media/uploads/:id/complete',
    auth: 'session',
    membership: 'BY_MEDIA_CLASS',
    ownership: 'Uploads created by the caller’s account only (others answer NOT_FOUND).',
    authorization: 'Re-checked at completion: the class rule must still hold.',
    validation: 'Object present, ≤ authorised size, content sniffed as the declared image type, decodable; re-encoded without metadata.',
    response: 'CompletedUpload',
    errors: [...MEMBER, 'NOT_ALLOWED', 'NOT_FOUND'],
  },
  'storage.upload': {
    method: 'PUT',
    path: '/v1/storage/upload',
    auth: 'signed-url',
    membership: 'NONE',
    ownership: 'Exactly the object key in the signed url.',
    authorization: 'HMAC signature over method, bucket, key, content type, length and expiry (local storage driver only).',
    validation: 'Signature, expiry, Content-Type equals the signed type, body length equals the signed length.',
    response: '{ stored }',
    errors: ['NOT_FOUND', 'VALIDATION_FAILED', 'PAYLOAD_TOO_LARGE'],
    bodyLimit: 8 * 1024 * 1024,
    when: 'local-storage',
  },
  'storage.object': {
    method: 'GET',
    path: '/v1/storage/object',
    auth: 'signed-url',
    membership: 'NONE',
    ownership: 'Exactly the object key in the signed url.',
    authorization: 'HMAC signature over method, bucket, key and expiry (local storage driver only).',
    validation: 'Signature and expiry (≤ 15 minutes ahead).',
    response: 'image/jpeg bytes',
    errors: ['NOT_FOUND'],
    when: 'local-storage',
  },

  // --- Admission ------------------------------------------------------------------------------------
  'admission.mine': {
    method: 'GET',
    path: '/v1/me/application',
    auth: 'session',
    membership: 'ACCOUNT',
    ownership: SELF_APP,
    authorization: 'Own application; summary never includes the date of birth.',
    validation: 'None.',
    response: 'MyApplication',
    errors: [...AUTHN, 'INTERNAL'],
  },
  'admission.submitStage1': {
    method: 'POST',
    path: '/v1/application',
    auth: 'session',
    membership: 'ACCOUNT',
    ownership: SELF,
    authorization: 'One application per account; submission moves only to APPLICATION_RECEIVED.',
    validation: 'Idempotency-Key; validateStage1Submission (names, DOB 18+, Instagram, country, city, referral).',
    response: 'MembershipApplication',
    errors: BASE,
  },
  'admission.startExtended': {
    method: 'POST',
    path: '/v1/application/extended/start',
    auth: 'session',
    membership: 'APPLICATION',
    ownership: SELF_APP,
    authorization: 'Only from EXTENDED_APPLICATION_REQUIRED (idempotent once started).',
    validation: 'None.',
    response: 'MyApplication',
    errors: [...BASE, 'NOT_ALLOWED'],
  },
  'admission.submitStage2': {
    method: 'POST',
    path: '/v1/application/extended',
    auth: 'session',
    membership: 'APPLICATION',
    ownership: SELF_APP,
    authorization: 'Only from EXTENDED_APPLICATION_DRAFT; photos must be the applicant’s own; moves to FINAL_REVIEW, never a decision.',
    validation: 'Idempotency-Key; validateStage2Submission.',
    response: 'MembershipApplication',
    errors: [...BASE, 'NOT_ALLOWED'],
  },
  'admission.respondToRequest': {
    method: 'PUT',
    path: '/v1/application/information-requests/:id/response',
    auth: 'session',
    membership: 'APPLICATION',
    ownership: 'Requests of the caller’s own application only.',
    authorization: 'Only in MORE_INFORMATION_REQUIRED; the answer touches only the request’s own target.',
    validation: 'validateResponse (type matches the request; media uploaded for this request).',
    response: 'MyApplication',
    errors: [...BASE, 'NOT_ALLOWED'],
  },
  'admission.submitInformationUpdate': {
    method: 'POST',
    path: '/v1/application/information-update',
    auth: 'session',
    membership: 'APPLICATION',
    ownership: SELF_APP,
    authorization: 'Every open request answered; returns to the review stage it came from.',
    validation: 'Idempotency-Key.',
    response: 'MyApplication',
    errors: [...BASE, 'NOT_ALLOWED'],
  },
  'admission.beginMembership': {
    method: 'POST',
    path: '/v1/membership/begin',
    auth: 'session',
    membership: 'APPLICATION',
    ownership: SELF_APP,
    authorization: 'Only from APPROVED; moves to MEMBERSHIP_PAYMENT_REQUIRED, never ACTIVE_MEMBER.',
    validation: 'None.',
    response: 'MyApplication',
    errors: [...BASE, 'NOT_ALLOWED'],
  },
  'admission.membershipPlans': {
    method: 'GET',
    path: '/v1/membership/plans',
    auth: 'session',
    membership: 'APPLICATION',
    ownership: 'Public plan data.',
    authorization: 'Only in APPROVED or MEMBERSHIP_PAYMENT_REQUIRED.',
    validation: 'None.',
    response: 'MembershipPlan[]',
    errors: [...AUTHN, 'NOT_ALLOWED', 'INTERNAL'],
  },

  // --- Member -------------------------------------------------------------------------------------------
  'member.me': {
    method: 'GET',
    path: '/v1/member/me',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: SELF_MEMBER,
    authorization: 'Membership checked in the same transaction.',
    validation: 'None.',
    response: 'OwnMember',
    errors: MEMBER,
  },
  'member.confirmProfile': {
    method: 'POST',
    path: '/v1/member/me/confirm',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: SELF_MEMBER,
    authorization: 'Membership.',
    validation: 'None.',
    response: 'OwnMember',
    errors: MEMBER,
  },
  'member.updateProfile': {
    method: 'PATCH',
    path: '/v1/member/me/profile',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: SELF_MEMBER,
    authorization: 'Only public profile fields; application records untouched; photo order only over own, unpurged photos.',
    validation: 'Types, then validateMemberProfilePatch.',
    response: 'OwnMember',
    errors: MEMBER,
    limits: ['profileUpdatePerMember'],
  },
  'member.datingSettings': {
    method: 'GET',
    path: '/v1/member/me/dating',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: SELF_MEMBER,
    authorization: 'Own private Dating settings only (never on any other member’s read).',
    validation: 'None.',
    response: 'OwnDatingSettings',
    errors: MEMBER,
  },
  'member.saveDatingSettings': {
    method: 'PUT',
    path: '/v1/member/me/dating',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: SELF_MEMBER,
    authorization: 'Only members who joined for Dating.',
    validation: 'validateDatingSettingsInput.',
    response: 'OwnDatingSettings',
    errors: [...MEMBER, 'NOT_ALLOWED'],
    limits: ['datingSettingsPerMember'],
  },
  'member.blocked': {
    method: 'GET',
    path: '/v1/member/me/blocked',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'Blocks the caller made.',
    authorization: 'Membership.',
    validation: 'None.',
    response: 'BlockedMember[]',
    errors: MEMBER,
  },
  'member.introductionsToday': {
    method: 'GET',
    path: '/v1/introductions/today',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'The caller’s own batch.',
    authorization: 'Dating members with completed setup; candidates pass the shared eligibility function (mutual preferences, blocks, membership, history).',
    validation: 'None.',
    response: 'IntroductionsView',
    errors: MEMBER,
  },
  'member.react': {
    method: 'POST',
    path: '/v1/introductions/:id/reaction',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'Introductions addressed to the caller only (others: INTRODUCTION_NOT_FOUND).',
    authorization: 'Today’s introduction, still eligible; one reaction per introduction; one ACTIVE match per pair.',
    validation: 'type ∈ {LIKE, PASS}.',
    response: 'ReactionResult',
    errors: [...MEMBER, 'INTRODUCTION_NOT_FOUND', 'INTRODUCTION_EXPIRED', 'REACTION_ALREADY_RECORDED', 'NOT_ELIGIBLE'],
    limits: ['reactionPerMember'],
  },
  'member.member': {
    method: 'GET',
    path: '/v1/members/:id',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'Another member’s PUBLIC profile only.',
    authorization: 'Introduced today (still eligible) or actively matched; never across a block.',
    validation: 'None.',
    response: 'PublicMemberDTO',
    errors: [...MEMBER, 'NOT_AVAILABLE'],
  },
  'member.block': {
    method: 'POST',
    path: '/v1/members/:id/block',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'The caller blocks someone they can see.',
    authorization: 'Visible to the caller (or already blocked). Ends an active match (BLOCKED) and closes its conversation.',
    validation: 'None.',
    response: '{ blocked }',
    errors: [...MEMBER, 'NOT_AVAILABLE'],
  },
  'member.report': {
    method: 'POST',
    path: '/v1/members/:id/reports',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'A member the caller can see or has blocked; only a conversation between the two can be attached.',
    authorization: 'Membership + visibility.',
    validation: 'reason, context, optional conversationId.',
    response: '{ reported }',
    errors: [...MEMBER, 'NOT_AVAILABLE'],
    limits: ['reportPerMember'],
  },
  'member.match': {
    method: 'GET',
    path: '/v1/matches/:id',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'Matches the caller is part of.',
    authorization: 'ACTIVE match, both sides active, no block.',
    validation: 'None.',
    response: 'MatchView',
    errors: [...MEMBER, 'MATCH_NOT_FOUND'],
  },
  'member.openConversation': {
    method: 'POST',
    path: '/v1/matches/:id/conversation',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'Matches the caller is part of.',
    authorization: 'ACTIVE match only; creates the conversation once.',
    validation: 'None.',
    response: 'ConversationView',
    errors: [...MEMBER, 'MATCH_NOT_FOUND'],
  },
  'member.conversations': {
    method: 'GET',
    path: '/v1/conversations',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'The caller’s active matches.',
    authorization: 'Membership.',
    validation: 'None.',
    response: 'ConversationSummary[]',
    errors: MEMBER,
  },
  'member.sendMessage': {
    method: 'POST',
    path: '/v1/conversations/:id/messages',
    auth: 'session',
    membership: 'ACTIVE_MEMBER',
    ownership: 'Conversations the caller participates in.',
    authorization: 'canSendMessage: participant, ACTIVE match, other side active, conversation open, no block.',
    validation: 'clientMessageId, validateMessage (text, 1–2000).',
    response: 'ThreadMessage',
    errors: [...MEMBER, 'CONVERSATION_FORBIDDEN'],
    limits: ['messagePerMinute', 'messagePerDay'],
  },

  // --- Internal (signed requests, scoped keys) ----------------------------------------------------------
  'internal.reviewQueue': {
    method: 'GET',
    path: '/internal/reviewer/applications',
    auth: 'internal',
    scope: 'review:read',
    membership: 'NONE',
    ownership: 'Submitted applications of active accounts (QA accounts only with includeQa=true).',
    authorization:
      'Read-only. The minimum to recognise a person — first name, age, city — plus the status and the reviewer actions open in it. No surname, phone number, answers or media.',
    validation: 'Optional query: status (comma-separated non-transient statuses), includeQa (true|false), limit (1–200, default 100); no other keys.',
    response: '{ applications: ReviewQueueItem[] } (oldest change first)',
    errors: INTERNAL,
  },
  'internal.reviewApplication': {
    method: 'GET',
    path: '/internal/reviewer/applications/:id',
    auth: 'internal',
    scope: 'review:read',
    membership: 'NONE',
    ownership: 'Any submitted application of an account that is not being deleted.',
    authorization:
      'Every open written to application_access_log (key id + reviewer id). Never a phone number (the applicant’s or a referrer’s); media as ids only — each photo is opened through review:media.',
    validation: 'Query: reviewerId (required); no other keys.',
    response: 'ReviewDetail',
    errors: INTERNAL,
  },
  'internal.reviewerAction': {
    method: 'POST',
    path: '/internal/reviewer/applications/:id/actions',
    auth: 'internal',
    scope: 'review:write',
    membership: 'NONE',
    ownership: 'Any application.',
    authorization: 'planReviewerAction (shared lifecycle); audited with the reviewer id.',
    validation: 'reviewerId, action.',
    response: 'MembershipApplication',
    errors: INTERNAL,
  },
  'internal.reviewerMedia': {
    method: 'POST',
    path: '/internal/reviewer/applications/:id/media/:mediaId/access',
    auth: 'internal',
    scope: 'review:media',
    membership: 'NONE',
    ownership: 'Media of that application.',
    authorization: 'Every access written to media_access_log; verification urls live 2 minutes.',
    validation: 'reviewerId, purpose ∈ {REVIEW, SAFETY}.',
    response: '{ url, expiresInSeconds, mediaClass }',
    errors: INTERNAL,
  },
  'internal.invitedMembership': {
    method: 'POST',
    path: '/internal/reviewer/applications/:id/invited-membership',
    auth: 'internal',
    scope: 'membership:complimentary',
    membership: 'NONE',
    ownership: 'That application’s account.',
    authorization:
      'Staging only (scope refused in production, route absent there). Only from APPROVED or MEMBERSHIP_PAYMENT_REQUIRED of an active account; the normal lifecycle and audit (actor: the reviewer). Membership marked complimentary with the reviewer who started it; no billing event, no renewal. Idempotent for an invited member.',
    validation: 'reviewerId; no other keys.',
    response: 'MembershipApplication',
    errors: INTERNAL,
    when: 'not-production',
  },
  'internal.paymentConfirmed': {
    method: 'POST',
    path: '/internal/billing/payment-confirmed',
    auth: 'internal',
    scope: 'billing:write',
    membership: 'NONE',
    ownership: 'The account named by the provider event.',
    authorization: 'Only from MEMBERSHIP_PAYMENT_REQUIRED; once per provider event id.',
    validation: 'accountId, providerEventId, provider.',
    response: 'MembershipApplication',
    errors: INTERNAL,
  },
  'internal.membershipExpired': {
    method: 'POST',
    path: '/internal/billing/membership-expired',
    auth: 'internal',
    scope: 'billing:write',
    membership: 'NONE',
    ownership: 'The account named by the provider event.',
    authorization: 'Only from ACTIVE_MEMBER; once per provider event id.',
    validation: 'accountId, providerEventId, provider.',
    response: 'MembershipApplication',
    errors: INTERNAL,
  },
  'internal.suspend': {
    method: 'POST',
    path: '/internal/safety/accounts/:id/suspend',
    auth: 'internal',
    scope: 'safety:write',
    membership: 'NONE',
    ownership: 'Any account.',
    authorization: 'active → suspended; every session revoked; audited.',
    validation: 'actorId, reasonCode.',
    response: '{ accountStatus, sessionsRevoked }',
    errors: INTERNAL,
  },
  'internal.reinstate': {
    method: 'POST',
    path: '/internal/safety/accounts/:id/reinstate',
    auth: 'internal',
    scope: 'safety:write',
    membership: 'NONE',
    ownership: 'Any account.',
    authorization: 'suspended → active; audited.',
    validation: 'actorId.',
    response: '{ accountStatus }',
    errors: INTERNAL,
  },
  'internal.placeHold': {
    method: 'POST',
    path: '/internal/safety/accounts/:id/holds',
    auth: 'internal',
    scope: 'safety:write',
    membership: 'NONE',
    ownership: 'Any account.',
    authorization: 'Keeps the account’s records out of anonymization and purges; audited.',
    validation: 'actorId, reason.',
    response: '{ holdId }',
    errors: INTERNAL,
  },
  'internal.releaseHold': {
    method: 'POST',
    path: '/internal/safety/holds/:id/release',
    auth: 'internal',
    scope: 'safety:write',
    membership: 'NONE',
    ownership: 'Any hold.',
    authorization: 'Audited.',
    validation: 'actorId.',
    response: '{ released }',
    errors: INTERNAL,
  },
  'internal.retentionRun': {
    method: 'POST',
    path: '/internal/retention/run',
    auth: 'internal',
    scope: 'retention:run',
    membership: 'NONE',
    ownership: 'System-wide.',
    authorization: 'Applies the configured retention policy; holds respected. dryRun: counts only, nothing changed.',
    validation: 'Optional { dryRun: boolean }; no other keys.',
    response: 'RetentionReport (counts and configured windows only)',
    errors: INTERNAL,
  },
  'internal.mediaReconcile': {
    method: 'POST',
    path: '/internal/media/reconcile',
    auth: 'internal',
    scope: 'media:reconcile',
    membership: 'NONE',
    ownership: 'System-wide (both buckets).',
    authorization:
      'Dry run by default; one run at a time. repair deletes only raw uploads no live upload can use, objects the database already purged, and unreferenced media-bucket objects older than a day; never a verification object without a record, never anything under a retention hold.',
    validation: "Optional { mode: 'dry-run' | 'repair' }; no other keys.",
    response: 'ReconcileReport (counts, opaque keys and ids only)',
    errors: INTERNAL,
  },
  'internal.testClientAddress': {
    method: 'POST',
    path: '/internal/test/client-address',
    auth: 'internal',
    scope: 'test:review',
    membership: 'NONE',
    ownership: 'The caller’s own address only.',
    authorization: 'Staging/test only (scope refused in production, route absent there). Verifies TRUST_PROXY_HOPS on a deployment; the staging tools also use it as a preflight before any OTP request.',
    validation: 'None.',
    response: '{ address, privateRange, hops }',
    errors: INTERNAL,
    when: 'not-production',
  },
  'internal.testReview': {
    method: 'POST',
    path: '/internal/test/applications/:id/review',
    auth: 'internal',
    scope: 'test:review',
    membership: 'NONE',
    ownership: 'QA applications only (accounts from designated test numbers); any other id answers NOT_FOUND.',
    authorization:
      'Staging/test only (scope refused in production, route absent there). Normal reviewer transition validation and audit; activation through the normal payment-confirmed path.',
    validation: 'action: START_REVIEW | REQUEST_EXTENDED | REQUEST_IDENTITY | APPROVE | WAITLIST | NOT_ADMIT | ACTIVATE.',
    response: 'MembershipApplication',
    errors: INTERNAL,
    when: 'not-production',
  },
  'internal.testLookup': {
    method: 'POST',
    path: '/internal/test/applications/lookup',
    auth: 'internal',
    scope: 'test:review',
    membership: 'NONE',
    ownership: 'Active QA accounts only (designated test numbers or listed project SIMs); any other number answers NOT_FOUND.',
    authorization: 'Staging/test only (scope refused in production, route absent there). Read-only: the application id and status of a QA number, for the reviewer side of a real-SIM journey.',
    validation: 'phoneE164.',
    response: '{ applicationId, status }',
    errors: INTERNAL,
    when: 'not-production',
  },
  'internal.testOtp': {
    method: 'POST',
    path: '/internal/test/otp',
    auth: 'internal',
    scope: 'test:otp',
    membership: 'NONE',
    ownership: 'Designated TEST numbers only (SMS_TEST_NUMBERS).',
    authorization: 'Staging/test only (scope refused in production, route absent there); each code readable once.',
    validation: 'phoneE164.',
    response: '{ code }',
    errors: INTERNAL,
    when: 'not-production',
  },
} as const satisfies Record<string, EndpointPolicy>;

export type EndpointId = keyof typeof ENDPOINTS;
