/**
 * Renders the endpoint policy registry as the table in docs/SECURITY_MODEL.md
 * (npm run docs:security). A test fails when the document and the registry
 * disagree, so the documentation always describes what the code enforces.
 */
import { ENDPOINTS, type EndpointPolicy } from './endpoints';

export const MATRIX_BEGIN = '<!-- endpoint-matrix:begin (generated by `npm run docs:security` from server/src/http/endpoints.ts — do not edit by hand) -->';
export const MATRIX_END = '<!-- endpoint-matrix:end -->';

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function renderEndpointMatrix(): string {
  const rows = (Object.entries(ENDPOINTS) as [string, EndpointPolicy][]).map(([id, p]) => {
    const auth = p.auth === 'internal' ? `internal (${p.scope})` : p.auth;
    const where = p.when === 'local-storage' ? ' (local storage driver only)' : p.when === 'not-production' ? ' (absent in production)' : '';
    return `| \`${p.method} ${p.path}\`${where} | ${auth} | ${p.membership} | ${cell(p.ownership)} | ${cell(p.authorization)} | ${cell(p.validation)} | ${cell(p.response)} | ${p.errors.join(', ') || '—'} | ${(p.limits ?? []).join(', ') || '—'} | \`${id}\` |`;
  });
  return [
    MATRIX_BEGIN,
    '',
    '| Endpoint | Auth | Membership | Ownership | Authorization | Validation | Response | Errors | Rate limits | Policy id |',
    '|---|---|---|---|---|---|---|---|---|---|',
    ...rows,
    '',
    MATRIX_END,
  ].join('\n');
}

/** Replace the generated block inside a document (or append it). */
export function withMatrix(doc: string): string {
  const block = renderEndpointMatrix();
  const a = doc.indexOf(MATRIX_BEGIN);
  const b = doc.indexOf(MATRIX_END);
  if (a === -1 || b === -1) return `${doc.trimEnd()}\n\n${block}\n`;
  return `${doc.slice(0, a)}${block}${doc.slice(b + MATRIX_END.length)}`;
}
