/**
 * All user-facing copy for the admission flow. Source: docs/COPY_AND_TONE.md.
 * Kept in one module so Turkish localisation can replace it wholesale.
 */
import type { ApplicationStatus } from '@/domain/admission/status';
import type { DobError } from '@/domain/validation/dateOfBirth';
import type { InstagramError } from '@/domain/validation/instagram';
import type { NameError } from '@/domain/validation/name';

export const copy = {
  /** Staging builds only (DEC-078). */
  staging: { mark: 'Staging', a11y: 'Staging build — test environment' },
  common: {
    continue: 'Continue',
    back: 'Back',
    retry: 'Try again',
    networkError: "We couldn't connect. Try again.",
    stepOf: (n: number, total: number) => `${n} of ${total}`,
    stepOfA11y: (n: number, total: number) => `Question ${n} of ${total}`,
    signOut: 'Sign out',
  },

  launch: {
    line: 'A private community, considered one person at a time.',
    apply: 'Apply for membership',
    signIn: 'I’ve already applied',
    photoA11y: 'A ferry deck on the Bosphorus in morning mist',
  },

  phone: {
    headline: 'What’s your number?',
    supporting: 'We’ll send you a verification code.',
    label: 'Mobile number',
    countryA11y: (name: string, code: string) => `Country code: ${name}, plus ${code}. Change`,
    codeLabel: 'Code',
    privacy: 'Your number is never shown to anyone.',
    errors: {
      required: 'Enter your mobile number.',
      invalid_number: 'Check your phone number and try again.',
      code_not_sent: 'We couldn’t send a code right now. Try again.',
      rate_limited: (seconds: number) =>
        seconds > 90
          ? 'Too many codes requested. Try again later.'
          : `Please wait ${seconds} seconds before requesting another code.`,
    },
    pickCountry: 'Country code',
  },

  otp: {
    headline: 'Enter your code',
    supporting: (phone: string) => `We sent a verification code to ${phone}.`,
    label: 'Verification code',
    a11yHint: 'Six digits. You can paste the code from your messages.',
    verify: 'Verify',
    resend: 'Resend code',
    resendIn: (s: number) => `Resend code in 0:${String(s).padStart(2, '0')}`,
    resent: 'A new code is on its way.',
    changeNumber: 'Use a different number',
    devHint: (code: string) => `Development build — use ${code}`,
    errors: {
      invalid_code: 'That code doesn’t look right. Try again.',
      attemptsLeft: (n: number) => (n === 1 ? 'One attempt left.' : `${n} attempts left.`),
      code_expired: 'This code has expired. Request a new one.',
      too_many_attempts: 'Too many attempts. Request a new code.',
    },
  },

  intro: {
    headline: 'Apply for membership',
    supporting: 'Membership is considered individually. Tell us a little about yourself.',
    detail:
      'It takes about two minutes. Your answers stay private to our membership team, and you can review everything before you submit.',
    cta: 'Begin application',
  },

  firstName: {
    headline: 'What’s your first name?',
    label: 'First name',
  },
  lastName: {
    headline: 'And your last name?',
    supporting: 'This stays private during the application process unless we tell you otherwise.',
    label: 'Last name',
  },
  nameErrors: {
    required: 'Enter your name as you usually write it.',
    too_long: 'That’s longer than we can store. Try a shorter form.',
    invalid_characters: 'Use letters only — hyphens and apostrophes are fine.',
  } satisfies Record<NameError, string>,

  dob: {
    headline: 'When were you born?',
    supporting: 'You must be 18 or older to apply.',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    groupA11y: 'Date of birth',
    privacy: 'Only your age could ever be shown — never your date of birth.',
    errors: {
      incomplete: 'Enter the day, month and full year.',
      impossible_date: 'That date doesn’t exist. Check the day and month.',
      future_date: 'That date is in the future.',
      implausible_date: 'Check the year.',
      under_minimum_age: 'You must be 18 or older to apply for membership.',
    } satisfies Record<DobError, string>,
  },

  instagram: {
    headline: 'What’s your Instagram?',
    supporting: 'It helps us understand a little more about you.',
    label: 'Instagram username',
    placeholder: 'username',
    privacy: 'Seen only by our membership team. It doesn’t appear on a profile.',
    errors: {
      required: 'Enter your Instagram username.',
      invalid_handle: 'Usernames use letters, numbers, full stops and underscores.',
      not_a_profile_link: 'Paste a link to your profile, not to a post.',
    } satisfies Record<InstagramError, string>,
  },

  country: {
    headline: 'Where are you based?',
    supporting: 'Choose your country.',
    search: 'Search countries',
    empty: (q: string) => `No country matches “${q}”.`,
  },

  city: {
    headline: 'Which city do you call home?',
    search: 'Search cities',
    useTyped: (q: string) => `Use “${q}”`,
    notListed: 'Not listed? Type your city’s name.',
    invalidTyped: 'Use your city’s name in letters.',
  },

  referral: {
    headline: 'Who can vouch for you?',
    supporting: 'If you know an existing member, you can add them as a referral.',
    add: 'Add a referral',
    addAnother: 'Add another referral',
    none: 'I don’t have a referral',
    nameLabel: 'Their name',
    phoneLabel: 'Their mobile number',
    save: 'Add referral',
    cancel: 'Cancel',
    remove: 'Remove',
    removeA11y: (name: string) => `Remove referral ${name}`,
    requested: 'Referral requested',
    explainer:
      'We contact them privately. For everyone’s privacy we never confirm whether someone is a member, and a referral is one part of your application — not a guarantee.',
    noneChosen: 'You’re applying without a referral. That’s completely fine.',
    errors: {
      name: 'Enter their name.',
      phone: 'Check their number.',
      duplicate: 'You’ve already added this person.',
      self: 'Add someone other than yourself.',
    },
  },

  review: {
    headline: 'Review your application',
    supporting: 'Make sure everything looks right before submitting. Tap any underlined answer to change it.',
    submit: 'Submit application',
    privacy: 'Your phone number is used to sign in and is never shown to anyone.',
    verifiedPhone: (phone: string) => `Verified number ${phone}`,
    readback: {
      name: 'My name is ',
      born: 'Born ',
      based: 'Based in ',
      instagram: 'On Instagram as ',
      referral: 'Referral requested from ',
      noReferral: 'Applying without a referral',
      and: ' and ',
      notes: {
        lastName: 'Your last name stays private.',
        dob: 'Only your age could ever be shown — never your date of birth.',
        instagram: 'Seen only by our membership team.',
        referral: 'Private. We never confirm who is a member.',
      },
    },
    confirmTitle: 'Submit your application?',
    confirmBody: 'Once submitted, your application will enter our membership review process. You won’t be able to change these answers.',
    confirmSubmit: 'Submit',
    confirmBack: 'Go back',
    submitting: 'Submitting your application…',
    failed: 'We couldn’t submit your application. Your answers are saved.',
    editAnswers: 'Edit answers',
    incomplete: 'A few answers are missing.',
  },

  received: {
    kicker: 'Membership application',
    headline: 'Application received',
    supporting: 'Thank you for applying. Every application is considered individually.',
    secondary: 'Your application status, and any update to it, will appear here in the app.',
    cta: 'View application status',
  },

  status: {
    /** Which letter this is: the application itself, or an update to it. */
    kicker: (status: string) =>
      status === 'EXTENDED_APPLICATION_REQUIRED' ||
      status === 'EXTENDED_APPLICATION_DRAFT' ||
      status === 'MORE_INFORMATION_REQUIRED' ||
      status === 'WAITLISTED'
        ? 'Application update'
        : 'Membership application',
    submittedOn: (date: string) => `Submitted ${date}`,
    details: {
      submitted: 'Submitted',
      nextStep: 'Your next step',
      updates: 'Updates',
      updatesValue: 'They will appear here.',
    },
    nothingNeeded: 'Nothing for now',
    stages: { received: 'Received', review: 'Review', finalReview: 'Final review', decision: 'Decision' },
    stageA11y: (current: string, rest: string[]) =>
      rest.length ? `Current stage: ${current}. Still to come: ${rest.join(', ')}.` : `Current stage: ${current}.`,
    yourApplication: 'Your application',
    currentStatus: 'Status',
    waitlistedValue: 'On the waitlist — still active',
    notAdmittedSecondary: 'Thank you for the time and care you put into your application.',
    approvedOn: (date: string) => `Approved ${date}`,
    updateReceived: 'Latest update',
    updateReceivedValue: (date: string) => `Received ${date}`,
    requests: {
      submit: 'Submit update',
      submitting: 'Sending your update…',
      readyToSend: 'Ready to send',
      change: 'Change',
      remaining: (n: number) => (n === 1 ? 'Complete the request above to send your update.' : `Complete the ${n} requests above to send your update.`),
      sent: 'Your update has been sent. Review continues.',
      failed: 'We couldn’t send your update. Your answers are saved — try again.',
    },
    onlyYou: 'Visible only to you and our membership team.',
    refreshing: 'Checking for updates…',
    checkForUpdates: 'Check for updates',
    devPanel: 'Development only — simulate a reviewer decision',
  },

  member: {
    redirecting: 'This area is for members.',
    loadFailed: 'We couldn’t load this.',
    welcome: {
      headline: 'You’re in.',
      body: 'Your membership is active. Before you meet anyone, take a moment with your profile.',
      cta: 'Continue',
      photoA11y: 'Your first photograph',
    },
    confirm: {
      chip: 'How members will see you',
      headline: 'This is your profile.',
      supporting: 'It was made from your application. You can change it at any time.',
      privacy:
        'Members see your first name, age and city — never your last name, date of birth, phone number, Instagram or what you told our membership team.',
      edit: 'Edit profile',
      cta: 'Enter the community',
    },
    tabs: { home: 'Home', messages: 'Messages', you: 'You', unread: 'new' },
    home: {
      kicker: 'Today’s introductions',
      more: 'More to come today',
      last: 'The last one today',
      open: (name: string) => `Open ${name}’s profile`,
      view: 'View profile',
      doneHeadline: 'That’s everyone for today.',
      doneBody: 'New introductions arrive tomorrow.',
      emptyHeadline: 'No introductions today.',
      emptyBody: 'We introduce members with care, so some days there is no one new. Check back tomorrow.',
      toMessages: 'Go to Messages',
      loadFailed: 'We couldn’t load today’s introductions.',
      // DEC-050: Today’s Introductions is Dating-only in V1. Friendship and community
      // discovery is a future surface — never promised with a date, never "nothing for you".
      notDatingHeadline: 'Dating introductions aren’t part of your experience right now.',
      notDatingBody: 'You joined for friendship and community. More community experiences will come later.',
      setupHeadline: 'One thing before your introductions.',
      setupBody: 'Tell us how you describe yourself, privately, so we only introduce people who are looking for each other.',
      setupAction: 'Continue',
    },
    profile: {
      knownFor: 'Known for',
      interests: 'Into',
      photoA11y: (i: number, n: number) => `Photo ${i} of ${n}`,
      pass: 'Pass',
      like: 'Like',
      passA11y: (name: string) => `Pass on ${name}`,
      likeA11y: (name: string) => `Like ${name}`,
      passed: (name: string) => `Passed. ${name} won’t be shown to you again today.`,
      liked: (name: string) => `Liked. If ${name} likes you too, you can start a conversation.`,
      next: 'Next introduction',
      nextShort: 'Next',
      backHome: 'Back to introductions',
      unavailable: 'This profile is no longer available.',
      more: 'More options',
      failed: 'That didn’t go through. Try again.',
      yours: 'How members see you',
    },
    safety: {
      report: (name: string) => `Report ${name}`,
      block: (name: string) => `Block ${name}`,
      reportTitle: 'What’s happening?',
      reasons: {
        NOT_GENUINE: 'This doesn’t seem like a real person',
        INAPPROPRIATE_PHOTOS: 'Inappropriate photos',
        HARASSMENT: 'Harassment or unwanted messages',
        SAFETY_CONCERN: 'I’m worried about someone’s safety',
        UNDER_18: 'They may be under 18',
        OTHER: 'Something else',
      } as Record<string, string>,
      reportNote: (name: string) => `Reports go to our membership team. ${name} won’t be told.`,
      reported: 'Thank you. Our membership team will look into it.',
      blockTitle: (name: string) => `Block ${name}?`,
      blockBody: (name: string) =>
        `${name} won’t be able to see your profile or message you, and won’t be told. Any conversation between you ends.`,
      blockConfirm: 'Block',
      blocked: (name: string) => `${name} is blocked.`,
      alsoBlock: (name: string) => `Also block ${name}`,
      done: 'Done',
      cancel: 'Cancel',
      failed: 'That didn’t go through. Try again.',
    },
    match: {
      headline: 'You should meet.',
      body: (name: string) => `You and ${name} both said yes.`,
      send: 'Send a message',
      keep: 'Keep exploring',
      you: 'You',
      photoA11y: (name: string) => `${name}’s first photo`,
    },
    messages: {
      title: 'Messages',
      emptyHeadline: 'No conversations yet.',
      emptyBody: 'When you and another member both say yes, you can talk here.',
      newMatch: 'You both said yes.',
      you: 'You: ',
      openA11y: (name: string) => `Conversation with ${name}`,
    },
    conversation: {
      introduced: (date: string) => `Introduced ${date}`,
      empty: 'You met through the community.',
      emptyNote: 'Messages are private to the two of you.',
      placeholder: 'Write a message',
      send: 'Send',
      today: 'Today',
      yesterday: 'Yesterday',
      failed: 'Not sent. Tap to try again.',
      closed: 'This conversation is no longer available.',
      viewProfile: (name: string) => `View ${name}’s profile`,
      tooLong: 'That message is too long.',
    },
    dating: {
      identityHeadline: 'How do you describe yourself?',
      identitySupporting:
        'Private. It never appears on your profile — we use it only to introduce people who are looking for each other.',
      genders: {
        WOMAN: 'Woman',
        MAN: 'Man',
        NON_BINARY: 'Non-binary',
        SELF_DESCRIBED: 'Self-describe',
      } as Record<string, string>,
      selfLabel: 'In your words',
      selfHint: 'Private. Up to 40 characters.',
      appearsLabel: 'Include me when people are looking to meet',
      appearsHint: 'Choose any that apply. What you wrote is never read or interpreted.',
      seekingHeadline: 'Who would you like to meet?',
      seekingSupporting: 'From your application — change it if you like. Private, like your answer before.',
      seekingEditSupporting: 'Private. Changes apply to future introductions.',
      categories: { WOMAN: 'Women', MAN: 'Men', NON_BINARY: 'Non-binary people', EVERYONE: 'Everyone' } as Record<string, string>,
      ageLabel: 'Age range',
      continue: 'Continue',
      save: 'Save',
      failed: 'We couldn’t save this. Try again.',
      errors: {
        gender: 'Choose how you describe yourself.',
        selfDescription: 'Write a few words, up to 40 characters.',
        appearsAs: 'Choose at least one.',
        seeking: 'Choose who you’d like to meet.',
        ageRange: 'Choose an age range.',
      } as Record<string, string>,
      preferencesTitle: 'Dating preferences',
      you: 'You',
      appearsAs: 'Included when people look to meet',
      seeking: 'Who you’d like to meet',
      ages: 'Ages',
      agesValue: (min: number, max: number) => `${min} to ${max}`,
      notSet: 'Not set yet',
      change: 'Change',
      privateNote:
        'Private. Members never see these. Changes apply to future introductions; your existing conversations stay as they are.',
      everyone: 'Everyone',
    },
    you: {
      viewProfile: 'View your profile',
      edit: 'Edit profile',
      datingPreferences: 'Dating preferences',
      membership: 'Membership',
      privacy: 'Privacy & safety',
      active: 'Active',
      signOut: 'Sign out',
    },
    edit: {
      title: 'Edit profile',
      photos: 'Photos',
      photosHint: 'The first photo leads your profile. Keep three to six.',
      photoA11y: (i: number, n: number) => `Photo ${i} of ${n}. Opens photo options.`,
      makeFirst: 'Make first photo',
      remove: 'Remove photo',
      add: 'Add',
      addA11y: 'Add a photo',
      minimum: 'Keep at least three photos.',
      occupation: 'Occupation',
      city: 'City',
      knownFor: 'Known for',
      knownForNote: 'Shown on your profile.',
      interests: 'Interests',
      change: 'Change',
      save: 'Save changes',
      saved: 'Saved.',
      applicationNote: 'Your application stays as you sent it. Only your profile changes.',
      errors: {
        occupation: 'Add your occupation.',
        cityLabel: 'Enter a city.',
        knownFor: 'Write at least a sentence or two.',
        interests: 'Choose three to eight interests.',
        photoOrder: 'Keep three to six photos.',
        save: 'We couldn’t save your changes. Try again.',
        upload: 'That photo didn’t upload. Try again.',
      } as Record<string, string>,
    },
    membershipScreen: {
      title: 'Membership',
      plan: 'Plan',
      planName: 'Membership',
      status: 'Status',
      since: 'Member since',
      renews: 'Renews',
      statuses: {
        active: 'Active',
        grace_period: 'Active — payment due',
        pending: 'Pending',
        cancelled: 'Cancelled',
        expired: 'Ended',
      } as Record<string, string>,
      billing: 'Billing settings will be available here.',
      planNameInvited: 'Invited membership',
      invited: 'Your membership was started by our membership team, by invitation. There is nothing to pay.',
    },
    privacy: {
      title: 'Privacy & safety',
      seeTitle: 'What members see',
      see: 'Your first name, age, city, occupation, what you’re known for, your interests and your photos.',
      neverTitle: 'What members never see',
      never:
        'Your last name, date of birth, phone number, Instagram, referrals, your dating preferences, your answers to our membership team, or your exact location.',
      locationTitle: 'Location',
      location: 'Only the city on your profile is shown. We never share where you are.',
      blockedTitle: 'Blocked members',
      noneBlocked: 'You haven’t blocked anyone.',
      blockedNote: 'Blocked members can’t see your profile or message you. They aren’t told.',
      reportingTitle: 'Reporting',
      reporting:
        'If something feels wrong, open “More options” on a profile or conversation to report or block. Reports go to our membership team.',
      screenshots: 'No app can prevent screenshots on every device. Share only what you’re comfortable sharing.',
      accountTitle: 'Your account',
      deleteRow: 'Delete account',
    },
    /** Account deletion (DEC-077): plain consequences, one clear confirmation, nothing to talk anyone out of it. */
    deleteAccount: {
      title: 'Delete account',
      intro: 'Your profile will be removed from the community and you will be signed out on every device.',
      whatHappensTitle: 'What happens',
      whatHappens: [
        'Your profile leaves the community straight away. Your matches and conversations end.',
        'Any membership ends.',
        'Your personal details and photos are then deleted.',
        'This can’t be undone. To return, you would apply again.',
      ],
      keptTitle: 'What may be kept',
      kept: 'Some records may be retained where needed for safety, security or legal obligations.',
      action: 'Delete account',
      confirmTitle: 'Delete your account?',
      confirmBody: 'You’ll be signed out now. This can’t be undone.',
      confirm: 'Yes, delete my account',
      cancel: 'Keep my account',
      errors: {
        network: 'We couldn’t connect. Your account hasn’t changed. Try again.',
        generic: 'Something went wrong. Your account hasn’t changed. Try again.',
      },
      done: 'Your account has been deleted and you’ve been signed out.',
    },
  },

  // --- Stage 2 — extended application (COPY_AND_TONE.md) -------------------------
  /** MORE_INFORMATION_REQUIRED tasks — titles and actions per structured request type. */
  request: {
    types: {
      REPLACE_PHOTO: { title: 'Replace a photo', action: 'Update photo' },
      VERIFY_IDENTITY: { title: 'Confirm it’s you', action: 'Confirm identity' },
      UPDATE_INSTAGRAM: { title: 'Check your Instagram', action: 'Update Instagram' },
      CLARIFY_WORK: { title: 'Clarify your work', action: 'Update work details' },
      UPDATE_APPLICATION_FIELD: { title: 'Add to an answer', action: 'Update answer' },
    },
    fieldTitle: { whatYouDo: 'What you’re known for', aboutYou: 'About you' } as Record<string, string>,
    current: 'Current',
    replacement: 'New',
    choosePhoto: 'Choose a new photo',
    chooseAnother: 'Choose a different photo',
    verifyGuide:
      'Take a clear, recent photo of your face in good light. It is used only to confirm your identity and never appears on your profile.',
    takePhoto: 'Take a photo',
    retakePhoto: 'Take another photo',
    verificationReceived: 'Photo received. Only our membership team can see it.',
    instagramLabel: 'Instagram username',
    occupationLabel: 'Occupation',
    workplaceLabel: 'Where you do it',
    save: 'Save',
    done: 'Done',
    uploading: 'Uploading…',
    errors: {
      upload: 'That photo didn’t upload. Try again.',
      save: 'We couldn’t save that. Try again.',
      invalid: 'Please check this and try again.',
    },
  },
  membership: {
    kicker: 'Membership',
    headline: 'Your membership',
    body: 'One step remains: activate your membership to join the community.',
    plan: 'Plan',
    billed: { monthly: 'Billed monthly', annual: 'Billed annually' } as Record<string, string>,
    per: { monthly: '/ month', annual: '/ year' } as Record<string, string>,
    fixtureNote: 'Development pricing — not final.',
    cta: 'Activate membership',
    unavailable: 'Membership activation will open here soon.',
    loading: 'Loading membership…',
    loadFailed: 'We couldn’t load membership details.',
    billingFailed: 'Activation didn’t complete. Nothing was charged — try again.',
    privacy: 'Your profile becomes visible to members only after activation.',
  },
  extended: {
    intro: {
      kicker: 'Application update',
      headline: 'We’d like to know you better.',
      supporting: 'Complete the next part of your application to continue the review process.',
      involvesLabel: 'What it involves',
      includes: 'A few photos, what you do, and a little about yourself.',
      timeLabel: 'Time',
      time: 'About ten minutes. Your answers save as you go.',
      privateLabel: 'Who sees it',
      private: 'Our membership team. Nothing is shown to members unless your membership is approved.',
      cta: 'Continue application',
    },
    photos: {
      headline: 'Show us who you are.',
      supporting: 'Choose recent photos that feel like you.',
      rule: (min: number, max: number) => `Add ${min} to ${max} recent photos. The large one introduces you.`,
      hint: 'The large photo introduces you. Tap any photo to move or remove it.',
      add: 'Add photo',
      addFirst: 'Add the photo that introduces you',
      addA11y: 'Add a photo from your library',
      addFirstA11y: 'Add the photo that introduces you, from your library',
      heroA11y: (n: number) => `Photo 1 of ${n}, the one that introduces you. Opens options.`,
      needMore: (n: number) => (n === 1 ? 'Add one more photo' : `Add ${n} more photos`),
      sheetTitle: (i: number, n: number) => `Photo ${i} of ${n}`,
      introduces: 'Introduces you',
      position: (i: number) => `Shown ${i === 2 ? 'second' : i === 3 ? 'third' : i === 4 ? 'fourth' : i === 5 ? 'fifth' : 'sixth'}`,
      lead: 'First',
      uploading: 'Uploading…',
      review: 'Reviewed before anyone sees them.',
      count: (n: number, max: number) => `${n} of ${max}`,
      photoA11y: (i: number, total: number) => `Photo ${i} of ${total}. Opens options.`,
      options: 'Photo',
      moveFirst: 'Make this your first photo',
      moveEarlier: 'Move earlier',
      moveLater: 'Move later',
      remove: 'Remove photo',
      cancel: 'Cancel',
      errors: {
        upload: 'That photo didn’t upload. Try again.',
        prepare: 'We couldn’t open that photo. Try a different one.',
        tooFew: (min: number) => `Add at least ${min} photos to continue.`,
      },
    },
    occupation: {
      headline: 'What do you do?',
      supporting: 'Use the description that feels most natural.',
      label: 'Occupation',
      placeholder: 'Architect, chef, founder…',
      shownAs: 'Shown beneath your name, as you write it.',
    },
    workContext: {
      headline: 'Where do you do it?',
      supporting: 'A company, studio or institution — or tell us you work independently.',
      organisation: 'At a company, studio or institution',
      organisationName: 'Name of the company, studio or institution',
      organisationPlaceholder: 'Its name',
      independent: 'Independently',
      notShared: 'I’d rather not say',
      optional: 'Optional.',
    },
    whatYouDo: {
      headline: 'What are you known for?',
      supporting: 'Tell us about the work, craft or pursuit that takes up your time.',
      label: 'What you’re known for',
      placeholder: 'The buildings you restore, the dishes people cross the city for, the research that keeps you up at night…',
      note: 'Shown on your profile, as you write it.',
    },
    aboutYou: {
      headline: 'What should we know about you?',
      supporting: 'Tell us something a profile or résumé wouldn’t.',
      label: 'About you',
      placeholder: 'Something a close friend would tell us about you.',
      note: 'For our membership team, not your profile.',
    },
    longTextCount: (n: number, max: number) => `${n} / ${max}`,
    longTextMin: (min: number) => `At least ${min} characters.`,
    interests: {
      headline: 'What are you into?',
      supporting: 'Choose the things you’d genuinely want to talk about.',
      count: (n: number, max: number) => `${n} / ${max}`,
      empty: 'Nothing chosen yet.',
      needMore: (n: number) => (n === 1 ? 'Choose one more.' : `Choose at least ${n} more.`),
      room: (n: number) => (n === 1 ? 'Room for one more.' : `Room for ${n} more.`),
      full: 'That’s your eight.',
      limit: (max: number) => `You can choose up to ${max}. Remove one to choose another.`,
      tabA11y: (label: string, n: number) => `${label}, ${n} chosen`,
    },
    intent: {
      headline: 'What brings you here?',
      supporting: 'Choose any that apply. You can change this later.',
      options: {
        dating: { label: 'Dating', detail: 'Meeting someone to date.' },
        friendship: { label: 'Friendship', detail: 'New people to know and spend time with.' },
        community: { label: 'Community', detail: 'Gatherings, places and a wider circle.' },
      },
    },
    meet: {
      headline: 'Who would you like to meet?',
      supporting: 'Choose any that apply. This is private — it never appears on your profile.',
      options: {
        women: 'Women',
        men: 'Men',
        non_binary: 'Non-binary people',
        everyone: 'Everyone',
      } as Record<string, string>,
    },
    ageRange: {
      headline: 'What age range feels right?',
      supporting: 'Private, like the question before. You can change it later.',
      from: 'From',
      to: 'To',
      youngest: 'Youngest age',
      oldest: 'Oldest age',
      increase: (what: string) => `Increase ${what.toLowerCase()}`,
      decrease: (what: string) => `Decrease ${what.toLowerCase()}`,
      readback: (min: number, max: number) => `Between ${min} and ${max}.`,
      limits: (min: number, max: number) => `Members are ${min} or older. The range can reach ${max}.`,
    },
    preview: {
      headline: 'This is how you’ll appear.',
      supporting:
        'Your profile won’t be visible to members unless your application is approved and membership is activated.',
      nameRule: 'Members would see your first name and age — never your last name or date of birth.',
      cta: 'Continue',
      chip: 'Only you can see this',
      photoA11y: (i: number, n: number) => `Photo ${i} of ${n}`,
      knownFor: 'Known for',
      interests: 'Into',
    },
    review: {
      headline: 'Ready for final review?',
      supporting: 'You can review your answers before submitting.',
      photos: 'Photos',
      work: 'Work',
      knownFor: 'Known for',
      about: 'About you',
      interests: 'Interests',
      intent: 'Here for',
      dating: 'Dating preferences',
      datingValue: 'Saved privately. Never shown on your profile.',
      aboutNote: 'Membership team only',
      editOccupation: 'Edit occupation',
      editWorkplace: 'Edit workplace',
      photosA11y: (n: number) => `Your ${n} photos, the first one large.`,
      photoCount: (n: number) => `${n} photos`,
      edit: 'Edit',
      editA11y: (section: string) => `Edit ${section}`,
      cta: 'Complete application',
      confirmTitle: 'Send for final review?',
      confirmBody:
        'Our membership team will consider your completed application. Completing it doesn’t guarantee membership.',
      confirmSubmit: 'Send',
      confirmBack: 'Go back',
      submitting: 'Sending your application…',
      failed: 'We couldn’t send your application. Your answers are saved.',
      independent: 'Independent',
    },
    sent: {
      kicker: 'Membership application',
      headline: 'Your application is in final review.',
      supporting: 'Thank you. Our membership team will consider your completed application.',
      secondary: 'Any update will appear on your application status.',
      cta: 'View application status',
    },
    errors: {
      required: 'Please answer this to continue.',
      too_short: (min: number) => `A little more, please — at least ${min} characters.`,
      too_long: 'That’s a little long. Try trimming it.',
      invalid_characters: 'Use letters and numbers — no emoji.',
    },
  },
} as const;

/**
 * Applicant-facing status copy — one entry per lifecycle state with a status
 * surface. `nextStep` answers "do I need to do anything?" in plain words.
 * No estimates, positions or probabilities (ADMISSION_FLOW §7–8).
 */
export type StatusCopy = { headline: string; body: string; nextStep: string; cta?: string };

export const statusCopy: Partial<Record<ApplicationStatus, StatusCopy>> = {
  APPLICATION_RECEIVED: {
    headline: 'Application received',
    body: 'Every application is considered individually. Review times vary.',
    nextStep: 'Nothing for now',
  },
  UNDER_REVIEW: {
    headline: 'Under review',
    body: 'Your application is being considered by our membership team. Review times vary for each application.',
    nextStep: 'Nothing for now',
  },
  EXTENDED_APPLICATION_REQUIRED: {
    headline: 'We’d like to know you better.',
    body: 'Complete the next part of your application to continue the review process.',
    nextStep: 'Continue your application',
    cta: 'Continue application',
  },
  EXTENDED_APPLICATION_DRAFT: {
    headline: 'Continue your application',
    body: 'Your answers so far are saved. Pick up where you left off.',
    nextStep: 'Finish the next part of your application',
    cta: 'Continue application',
  },
  EXTENDED_APPLICATION_SUBMITTED: {
    headline: 'Application sent',
    body: 'Your completed application is on its way to our membership team.',
    nextStep: 'Nothing for now',
  },
  FINAL_REVIEW: {
    headline: 'Final review',
    body: 'Your completed application is in final review with our membership team.',
    nextStep: 'Nothing for now',
  },
  MORE_INFORMATION_REQUIRED: {
    headline: 'We need a little more information.',
    body: 'Your application is still active. Complete the request below so we can continue the review.',
    nextStep: 'Complete the request below',
  },
  WAITLISTED: {
    headline: 'You’re on the waitlist',
    body: 'Your application remains active and may be reconsidered as the community evolves.',
    nextStep: 'Nothing for now',
  },
  APPROVED: {
    headline: 'Welcome.',
    body: 'Your membership application has been approved.',
    nextStep: 'Activate your membership',
    cta: 'Continue',
  },
  NOT_ADMITTED: {
    headline: 'Application update',
    body: 'We’re unable to offer membership at this time.',
    nextStep: 'Nothing further is needed',
  },
  MEMBERSHIP_PAYMENT_REQUIRED: {
    headline: 'Welcome.',
    body: 'Your membership is ready to be activated.',
    nextStep: 'Membership setup opens in a coming update',
  },
  SUSPENDED: { headline: 'Membership paused', body: 'Your membership is currently paused.', nextStep: 'Nothing for now' },
  EXPIRED: { headline: 'Membership ended', body: 'Your membership has ended.', nextStep: 'Nothing for now' },
};
