-- 0001 — Foundation: accounts, authentication, sessions, idempotency, rate limits.
--
-- Everything lives in the `app` schema. The API service is the only database
-- client (docs/BACKEND_ARCHITECTURE.md); 0004 closes the schema to every
-- other role. Identifiers are opaque text ids generated by the API.

CREATE SCHEMA IF NOT EXISTS app;

-- A person, identified by a verified phone number. Private: never public, never searchable.
CREATE TABLE app.accounts (
  id                 text PRIMARY KEY,
  phone_e164         text NOT NULL UNIQUE CHECK (phone_e164 ~ '^\+[0-9]{6,15}$'),
  phone_verified_at  timestamptz NOT NULL,
  account_status     text NOT NULL DEFAULT 'active' CHECK (account_status IN ('active', 'suspended', 'deleted')),
  created_at         timestamptz NOT NULL,
  updated_at         timestamptz NOT NULL
);

-- One-time codes. Only a keyed hash of the code is stored (HMAC-SHA256 with a
-- server secret), never the code. Earlier challenges for a number are
-- consumed when a new one is issued.
CREATE TABLE app.otp_challenges (
  id                   text PRIMARY KEY,
  phone_e164           text NOT NULL,
  code_hash            text NOT NULL,
  expires_at           timestamptz NOT NULL,
  resend_available_at  timestamptz NOT NULL,
  attempts             integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  consumed_at          timestamptz,
  created_at           timestamptz NOT NULL
);
CREATE INDEX otp_challenges_phone_idx ON app.otp_challenges (phone_e164, created_at DESC);

-- Sessions: the bearer token is shown to the client once; only its SHA-256 is stored.
CREATE TABLE app.sessions (
  token_hash   text PRIMARY KEY,
  account_id   text NOT NULL REFERENCES app.accounts (id),
  created_at   timestamptz NOT NULL,
  expires_at   timestamptz NOT NULL,
  revoked_at   timestamptz
);
CREATE INDEX sessions_account_idx ON app.sessions (account_id);

-- Client idempotency keys for submissions: the same key replays the same resource.
CREATE TABLE app.idempotency_keys (
  account_id   text NOT NULL REFERENCES app.accounts (id),
  operation    text NOT NULL,
  key          text NOT NULL CHECK (char_length(key) BETWEEN 1 AND 200),
  resource_id  text NOT NULL,
  created_at   timestamptz NOT NULL,
  PRIMARY KEY (account_id, operation, key)
);

-- Rate limits (sliding windows). One row per counted action; old rows are pruned.
CREATE TABLE app.rate_limit_events (
  bucket   text NOT NULL,
  subject  text NOT NULL,
  at       timestamptz NOT NULL
);
CREATE INDEX rate_limit_events_idx ON app.rate_limit_events (bucket, subject, at);
